name: Bio-Medpost
version: 0.01
abstract: Part of speech tagger for MEDLINE text
author: Yung-chung Lin <xern@cpan.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.34
